greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_tiger_bigquery:
      type: bigquery
      method: service-account
      project: durable-matter-414109
      dataset: dbt_tiger
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/dags/durable-matter-414109-dbt-a357d155397d.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: durable-matter-414109
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/YOUR-KEYFILE.json
      location: asia-southeast1

  target: dbt_tiger_bigquery